language: generic
sudo: required
dist: trusty

services:
- docker

install:
 - git reset --hard

script:
- export KUBEVIRT_UPDATE_CACHE_FROM="${TRAVIS_BRANCH}"
- export KUBEVIRT_CACHE_FROM="${TRAVIS_BRANCH}"
- if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then make pull-cache; fi # only use the cache in PRs, rebuild otherwise
- make generate
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make generate`. Please run it and commit the changes"; git status --porcelain; false; fi
- if diff <(git grep -c '') <(git grep -cI '') | egrep -v -e 'docs/.*\.png|swagger-ui' -e 'vendor/*'
  | grep '^<'; then echo "Binary files are present in git repostory."; false; fi
- make build
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make`. Please run it and commit the changes"; git status --porcelain; false; fi
- if [[ $TRAVIS_REPO_SLUG == "kubevirt/kubevirt" ]]; then make goveralls; else make test; fi
- make apidocs
- make client-python
- make manifests DOCKER_PREFIX="docker.io/kubevirt" DOCKER_TAG=$TRAVIS_TAG # falls back to latest if not on a tag

deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && make publish
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && KUBEVIRT_UPDATE_CACHE_FROM="${TRAVIS_BRANCH}" make push-cache
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $TRAVIS_BRANCH != revert-*
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && make publish DOCKER_TAG=$TRAVIS_TAG
  skip_cleanup: true
  file:
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: KD1d1EkvX5iY5pvKQbi6Aj6y49XXnQBxBMok9x2d9LVMbmzBQIHoTqUQz2Dv2TSpANshkIrLmR1eT/brCK382cIUVvA6kG8JB2yqAAE2hzJ8u49+CI4iyqpBWw1HCuH/4xPWZUPVBW0Yl9WsW0vencAeKK6cTDm4Z9K3esJf+iZMpJh7ZpK2ESn9d2RZsrpOKJpxYrvt14Wox+8YfqPRCTJoO/Q8vdXbyOrRVpK6daSe11HsmTZZpFzgLWGojpjH05wcENUaokpCIp8Hgx3rJmO9z5iReNG+2QuPCw0QyEIKGAvzlA5KbYFWBUurxz0XsnaovbJ7BKI070arxQKjKRnjSNE3kEValOwMIE8dA835A1nChm85NILQdWvlbexSxPpz0z62SGPjFthUj9VBx/RnUrd1itxWOi6ZW5k6PnWDUoKPr63+fYSAkp6bXO9ELexA19wUfQCicGRBEO3mJ6QvKKbiDAFKWcABlavxlNtFgw1mMPxxWEhKkW0PrCqOVu9fDDzJ48DCD5XHRT8HUVHDeKcscMTW675rlzo3SxTJdqnZSybpbMSmKbxNs0rM8kPXf1RQLsGDg4CC6Daxz255PV5Y/+p0AhZ2hWtfC3c/Ff8wOdDSdCaEcg5tGa/e1kJWAKuIATUGdZsFZUri8ePQcgcXzM4ihANn7gP8Cl4=
  file_glob: true
  file:
  - _out/cmd/virtctl/virtctl-v*
  - _out/manifests/release/kubevirt.yaml
  - _out/templates/manifests/release/kubevirt.yaml.j2
  - _out/manifests/release/demo-content.yaml
  - _out/manifests/release/kubevirt-operator.yaml
  - _out/manifests/release/kubevirt-cr.yaml
  - _out/templates/manifests/release/kubevirt-operator.yaml.j2
  - _out/templates/manifests/release/kubevirt-cr.yaml.j2
  prerelease: true
  overwrite: true
  name: $TRAVIS_TAG
  on:
    tags: true
    repo: kubevirt/kubevirt
- provider: script
  skip_cleanup: true
  script: bash hack/gen-swagger-doc/deploy.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash hack/gen-swagger-doc/deploy.sh
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: bash hack/gen-client-python/deploy.sh
  on:
    branch: master

env:
  global:
  # api-reference token
  - secure: pS1N+T7f20B9PJ2S6e4Bc0z0vK6wnUgtGrs1982iXYocVZZtL6LreXYV/9a5ANrykLx+/qeRxbR4FTknfJwsmm2MX1WN7FIEtp7wGxt5uU0Q+b5pERbgUL8amkvhc6Hj9eWn59fbEKSmAEeMupeYydPPCFJp8oumEEP6szb0zCj7LQPWxhEMtVLY2U8d3WbkhBoxC1Bv5kTOajaiyuwjgiJd3yvR6WfNOQUL167TCoyzRDoe7jUSZ9EScyDRg7mC2Nk2o4vzZwmaz8QjO6T6f2za95t7/kxhYrL7WAfa3POxdhHPP0XX4ZsypU6++hDj0txPAB/ICa55Za6A+BhFrUdGeoYb3T8jtWIF9UDHq6m8yhurtDPooR7VMjkR2ghz4Ol4cv2f1QWv5MGDg4hh9gKgjE+gbbeZyA5+t3l/Zf2HozZQCIDpMpi4EUUS3rCGkr44h0AjiZP9s4QrUY74kpT6GEGluFTlkXar+R3bvnTVY2J4vj6XGdAXHYtAbKI2/yaq20wqkbsC6BKHITcZ/E3eIBh2kc0WD4pdm8MnI0chuuMSkM6ynRDcPNYi235VmhxuUBaNWrkQEHGVOjXJPLB+xMRc6vVxAjV/OFaKXsbPb4aJl1TRJ1RclHAf4Am3SPuiowm8JmODTrmmYkF67rAGILO1oVxwmvwVLAmcJSI=
  # DOCKER_PASS
  - secure: dgqV8rjscJmensslnxAyjgFqWMffZwQYAAObtuJdpPwdyGBSCA9LUH0J++raGo++35JzbyGukdGZgKBAUVKyydFcStmIUfi7dB2eljMYU8dnTvlDWEP6PwhuQXdDDjbDqCDAWH8mfjza4qFw/XgHXw+dy2EikMKewE6IzfUquk3xyfkh3mutNTETu7E78yKfxh4bDejyakaJKADFzm2hvhJv/+pzkJuALGbG4v7qW1inW6/Qug+QK8ZYIIaNM/UmZOVgcnrt4+3UcCS2NS3bMFdibAZKNQVD6g0Jht+S6/RQIhT4zaW7eaKDAKhjUETKbZ4Xv/77h6huwAy9DxtKu/gWQ/7rp1xt6JU3oheVV705qxvA8mm7P61rqe4GaanTyOWQuIvKteVxIHuZKGkrtQS4Own3lgydLmkgM7u3cR33JA4tolZcf2kWXRFU8vwOlCM8Vsb7NJfu/yJ/0xuFJ/HNO6FLUZz3p2M2wW6WY17V0YKE7KXXiKhj3rv3RbsFBFfGiTXyk/nk0czQhA9e/87JepTTlZf3R9QSLoHs+cR4fEE+oAZOyAUeU5N1C703772YEjrxtXczE3qm4dUFS7UXNcjeYjWsLpMSbuqa49yYPMPCynu5ohSTTwjhweRFSJf7xmp18t3bMfGKiHx8rBCqCNDpC6fuTM5v/C5c1K4=
  # DOCKER_USER
  - secure: GDzAdyMI1IssB8je9PsidxUJ55Bp2+gTKh0bB+Syy50BWz81yxWsK0oHvM65h1DTPKv30lnwAvaOLy21uEBBuWNoyCCkMIdc9HeUwpi+Ilex9D84vDtf5c4tx3pIxpzNPOfm/7wWQDYI9o2eeGIY0B3WGufiUlelWC3i1Uq3r2OTfufxwMpwIyuHydU8VOvyromdiZ2VNZcCAmrpVONd+UBmxrvJoIINVN80XH7tlpSfdKC70VJGLyp3bwSPBHl8LkI1nkEwMB+1La+EPYmfE4hfHDiAeRYqiIEKR9VYmjh2O6Lo8VDMebLzC/kH8S1zQt71PN/Oknqu60jenPMz6gr4sKt17uE4+BH+7Ef+jp4uFqwYV7rGCg7vbE/fE3nW2GBcpXCNZZsVvKg+u3TrquvssszUZyNQmy2NOoeqdM6F4D1h5mqhyp/Rrg5VFpiwN92CLI0yfoCPHbZcLs8DLcZuxTDVhjoatUnTUs68hPFaY0q9SpFwRAsb6tVyuoMG2fHpBd7oZCZVrnQzHslrFulpzVqbm28x+jrPVBRTGmak79eZrckQ92FyLQQONiYP6g+V9dMiJ4tho4P5U84z2Ty8IQZTC7UDw+2ZpVNNud+NTGSal/K+eJ1XzPRDO0N3qZ6uOQG1kOkIn29Kh7/PqxLEcbZf4Ay5sL4IwzTrmx4=

notifications:
  irc:
    channels:
      - "chat.freenode.net#kubevirt"
    on_success: change
    on_failure: always
